stages:
  - build
  - deploy

docker:
  stage: build
  tags:
  - ecomm-2
  script:
    - ls
    - docker login registry.gitlab.com --username=$gitlabdockerusername --password=$gitlabdockerpassword
    - docker build -t registry.gitlab.com/anjireddy1804/ecomm:$version .
    - docker push registry.gitlab.com/anjireddy1804/ecomm:$version
  rules:
    - when: manual


deploy-prod:
  stage: deploy
  tags:
  - ecomm-2
  only:
    - master
  script: 
    - kubectl apply -f Deployment.yml
  
