stages:
  - build
  - deploy

docker:
  stage: build
  tags:
  - ecomm
  script:
    - ls
    - docker login --username=anjreddy --password=Adiyog!@112
    - docker build -t anjreddy/ecomm:dev .
    - docker push anjreddy/ecomm:dev
  rules:
    - when: manual


deploy-prod:
  stage: deploy
  tags:
  - ecomm
  only:
    - master
  script: 
    - echo 1234 | sudo -S kubectl apply -f Deployment.yml
  
