stages:
  - build
  - deploy

docker:
  stage: build
  tags:
  - ecomm
  script:
    - ls
    - docker login --username=$dockerusername --password=$dockerpassword
    - docker build -t anjreddy/ecomm:$version .
    - docker push anjreddy/ecomm:$version
  rules:
    - when: manual


deploy-prod:
  stage: deploy
  tags:
  - ecomm
  only:
    - master
  script: 
    - echo $gitlabpassword | sudo -S kubectl apply -f Deployment.yml
  
