apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecomm
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ecomm
    spec:
      containers:
      - name: ecomm
        image: registry.gitlab.com/anjireddy1804/ecomm:2.0.0
        ports:
        - containerPort: 80
         
---

apiVersion: v1
kind: Service
metadata:
  name: ecomm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ecomm
