apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm
  labels:
    app: ecomm
spec:
  selector:
    matchLabels:
      app: ecomm
  template:
    metadata:
      labels:
        app: ecomm
    spec:
      containers:
      - name: ecomm
        image: anjreddy/ecomm:latest
        ports:
        - containerPort: 80
         
---

apiVersion: v1
kind: Service
metadata:
  name: ecomm
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ecomm
