apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecomm-dev
  labels:
    app: ecomm-dev
spec:
  selector:
    matchLabels:
      app: ecomm-dev
  template:
    metadata:
      labels:
        app: ecomm-dev
    spec:
      containers:
      - name: ecomm-dev
        image: anjreddy/ecomm:dev
        ports:
        - containerPort: 80
         
---

apiVersion: v1
kind: Service
metadata:
  name: ecomm-dev
spec:
  type: NodePort
  ports:
    - port: 25
      targetPort: 80
  selector:
    app: ecomm-dev
